### ISSUE TITLE
Rollen

### ISSUE THREAD

**Issue by apalgen** [cc-fiae-2024/eventguru-app#11]
Als ein Administrator möchte ich Rollen für andere Administratoren und Veranstalter vergeben können, um Zugriffsrechte festzulegen.

**Comment by Ryuno-Ki** [comment]
@stevenobird Wenn du mit dem Deployment-Ticket (#5) fertig bist, sollten wir uns mit Rollen auseinander setzen.

Mein letzter Stand ist, dass wir die Laravel-User zunächst als Admins behandeln.
Davon abgeleitet kommen dann weitere wie Veranstalter und Besucher.

Kannst du mit @Gurutosh die Erwartungshaltungen / Berechtigungen pro Rolle näher spezifizieren und dokumentieren?

**Comment by stevenobird** [comment]
> Mein letzter Stand ist, dass wir die Laravel-User zunächst als Admins behandeln.

Ich würde eher jeden neuen Benutzer als "normalen" Benutter ohne besondere Berechtigungen ansehen.

> Davon abgeleitet kommen dann weitere wie Veranstalter und Besucher.

Genau. Veranstalter kann man über ein Formular werden, das von einem Admin (oder einer entsprechenden Person mit höheren Rechten/Rollen) bestätigt oder abgelehnt wird.

> Kannst du mit @Gurutosh die Erwartungshaltungen / Berechtigungen pro Rolle näher spezifizieren und dokumentieren?

Können wir morgen angehen, ja.
