### ISSUE TITLE
Anmeldung

### ISSUE THREAD

**Issue by apalgen** [cc-fiae-2024/eventguru-app#2]
**User Story**
Als ein registrierter Veranstalter möchte ich mich einloggen können, um meine Events zu verwalten.

**Issue Beschreibung**
Es muss das von Laravel vorgegebene Login Formular für Veranstalter angepasst werden. Zuvor sollte ein Mockup vom Designer erstellt werden.

![Default Laravel Login](https://github.com/user-attachments/assets/54127e3a-e05e-44ba-8524-488f99858588)

- [x] Mockup erstellen

**Comment by apalgen** [comment]
An @Gurutosh fürs Mockup übergeben

**Comment by apalgen** [comment]
Mockup ist fertig es kann weiter gehen

**Comment by Ryuno-Ki** [comment]
Wartet auf #3. Mockup gibt es bereits im Figma. Von Laravel wird bereits vieles bereitgestellt.
Wir brauchen eventuell auch #11, wenn es verschiedene Seiten geben soll, die nach einem Login angesprungen werden.

**Comment by Ryuno-Ki** [comment]
Ich nehm mir das als nächstes vor.

**Comment by Ryuno-Ki** [comment]
Siehe #52

**Comment by Ryuno-Ki** [comment]
Erledigt.
