### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by Ryuno-Ki** [cc-fiae-2024/eventguru-app#28]
Es muss eine Datenschutzerklärung erstellt werden

**Comment by Ryuno-Ki** [comment]
Die Datenschutzerklärung wird in Markdown im Repo als Datei gepflegt und von Laravel als HTML ausgespielt.

**Comment by iTouch87** [comment]
hier der erste Entwurf zum Datenschutz

Datenschutzerklärung für [www.eventguru.fun](http://www.eventguru.fun/)

1. Verantwortlicher
Verantwortlich für die Verarbeitung Ihrer personenbezogenen Daten im Sinne der EU-Datenschutzgrundverordnung (DSGVO) ist:

[Name des Betreibers]
[Adresse des Betreibers]
E-Mail: [E-Mail des Betreibers]
Telefon: [Telefonnummer des Betreibers]

2. Erhebung und Speicherung personenbezogener Daten sowie Art und Zweck der Verwendung
a) Beim Besuch der Website
Beim Aufrufen unserer Website [www.eventguru.fun](http://www.eventguru.fun/) werden automatisch Informationen an den Server unserer Website gesendet. Diese Informationen werden temporär in einem sogenannten Logfile gespeichert. Folgende Informationen werden dabei ohne Ihr Zutun erfasst und bis zur automatisierten Löschung gespeichert:

IP-Adresse des anfragenden Rechners,
Datum und Uhrzeit des Zugriffs,
Name und URL der abgerufenen Datei,
Website, von der aus der Zugriff erfolgt (Referrer-URL),
verwendeter Browser und ggf. das Betriebssystem Ihres Rechners sowie der Name Ihres Access-Providers.
Diese Daten werden zur Gewährleistung eines reibungslosen Verbindungsaufbaus der Website, zur Gewährleistung einer komfortablen Nutzung unserer Website, zur Auswertung der Systemsicherheit und -stabilität sowie zu weiteren administrativen Zwecken verarbeitet. Die Rechtsgrundlage für die Datenverarbeitung ist Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse folgt aus den oben aufgelisteten Zwecken zur Datenerhebung.

b) Bei der Registrierung als Nutzer
Wenn Sie sich als Nutzer auf unserer Plattform registrieren, erheben wir folgende Daten:

Name,
E-Mail-Adresse,
Passwort.
Diese Daten verarbeiten wir, um Ihnen den Zugang zu Ihrem Benutzerkonto zu ermöglichen und Ihnen die Nutzung der Plattform zu gestatten. Rechtsgrundlage hierfür ist Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung).

3. Nutzung des Kalenders und Event-Verwaltung
Im Rahmen der Kalender- und Event-Verwaltungsfunktion verarbeiten wir die von Ihnen eingestellten Informationen, wie:

Eventtitel,
Veranstaltungsort,
Veranstaltungsdatum,
sonstige beschreibende Angaben.
Diese Daten werden auf der Plattform veröffentlicht und sind für andere Nutzer sichtbar. Sie können diese Informationen jederzeit ändern oder löschen. Die Rechtsgrundlage hierfür ist Art. 6 Abs. 1 lit. b DSGVO.

4. Weitergabe von Daten
Eine Übermittlung Ihrer persönlichen Daten an Dritte findet nicht statt, es sei denn:

Sie haben nach Art. 6 Abs. 1 lit. a DSGVO Ihre ausdrückliche Einwilligung dazu erteilt,
die Weitergabe ist nach Art. 6 Abs. 1 lit. f DSGVO zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich und es besteht kein Grund zur Annahme, dass Sie ein überwiegendes schutzwürdiges Interesse an der Nichtweitergabe Ihrer Daten haben,
es besteht eine gesetzliche Verpflichtung für die Weitergabe nach Art. 6 Abs. 1 lit. c DSGVO,
dies ist gesetzlich zulässig und nach Art. 6 Abs. 1 lit. b DSGVO für die Abwicklung von Vertragsverhältnissen mit Ihnen erforderlich.
5. Speicherung und Löschung von Daten
Wir speichern Ihre personenbezogenen Daten nur so lange, wie dies zur Erfüllung der Zwecke erforderlich ist, für die sie erhoben wurden, oder wie es durch gesetzliche Vorschriften vorgeschrieben ist. Danach werden die Daten gemäß den gesetzlichen Vorgaben gelöscht.

6. Ihre Rechte
Sie haben das Recht:

gemäß Art. 15 DSGVO Auskunft über Ihre von uns verarbeiteten personenbezogenen Daten zu verlangen,
gemäß Art. 16 DSGVO unverzüglich die Berichtigung unrichtiger oder Vervollständigung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen,
gemäß Art. 17 DSGVO die Löschung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen,
gemäß Art. 18 DSGVO die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen,
gemäß Art. 20 DSGVO Ihre personenbezogenen Daten in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten oder die Übermittlung an einen anderen Verantwortlichen zu verlangen,
gemäß Art. 7 Abs. 3 DSGVO Ihre einmal erteilte Einwilligung jederzeit zu widerrufen,
gemäß Art. 77 DSGVO sich bei einer Aufsichtsbehörde zu beschweren.
7. Datensicherheit
Wir verwenden geeignete technische und organisatorische Sicherheitsmaßnahmen, um Ihre Daten gegen zufällige oder vorsätzliche Manipulationen, teilweisen oder vollständigen Verlust, Zerstörung oder unbefugten Zugriff Dritter zu schützen.

8. Aktualität und Änderung dieser Datenschutzerklärung
Diese Datenschutzerklärung ist aktuell gültig und hat den Stand Oktober 2024. Durch die Weiterentwicklung unserer Website oder aufgrund geänderter gesetzlicher Vorgaben kann es notwendig werden, diese Datenschutzerklärung zu ändern.

**Comment by Ryuno-Ki** [comment]
Danke dir!

@apalgen Ich würde unsere eventguru.fun-Adresse hinterlegen.

**Comment by Ryuno-Ki** [comment]
Integriert
