### ISSUE TITLE
AGBs

### ISSUE THREAD

**Issue by Ryuno-Ki** [cc-fiae-2024/eventguru-app#29]
Es muss eine AGB entworfen werden

**Comment by Ryuno-Ki** [comment]
Die AGB werden als Markdown-Datei im Repo gepflegt und von Laravel als HTML ausgespielt.

**Comment by iTouch87** [comment]
Hier der erste AGB Entwurf

Allgemeine Geschäftsbedingungen (AGB) für [www.eventguru.fun](http://www.eventguru.fun/)

§ 1 Geltungsbereich
(1) Diese Allgemeinen Geschäftsbedingungen (AGB) gelten für die Nutzung der Plattform [www.eventguru.fun](http://www.eventguru.fun/) (im Folgenden „Plattform“), die von [Plattformbetreiber] betrieben wird.
(2) Die Plattform bietet Veranstaltern die Möglichkeit, ihre Events zu präsentieren und über ein Kalendersystem zu verwalten. Die AGB gelten für alle Verträge zwischen dem Plattformbetreiber und den Nutzern der Plattform, die sich für ein Benutzerkonto registrieren.

§ 2 Vertragsgegenstand
(1) Der Plattformbetreiber stellt eine Online-Plattform zur Verfügung, auf der Veranstalter ihre Events präsentieren und über einen Kalender organisieren können.
(2) Die Plattform bietet Funktionen wie Event-Präsentation, Verwaltung von Terminen über einen Kalender und die Möglichkeit zur Benutzerregistrierung und -anmeldung.
(3) Der Plattformbetreiber stellt die technischen Voraussetzungen für die Nutzung der Plattform zur Verfügung, haftet jedoch nicht für die Inhalte, die von den Veranstaltern hochgeladen oder bereitgestellt werden.

§ 3 Registrierung und Benutzerkonto
(1) Die Nutzung der Plattform setzt eine Registrierung voraus. Hierbei sind die zur Registrierung erforderlichen Angaben vollständig und korrekt anzugeben.
(2) Jeder Nutzer ist verpflichtet, sein Passwort und die Zugangsdaten sicher zu verwahren und darf diese nicht an Dritte weitergeben.
(3) Der Plattformbetreiber behält sich das Recht vor, Benutzerkonten zu sperren oder zu löschen, falls ein Verstoß gegen diese AGB vorliegt.

§ 4 Nutzung der Plattform
(1) Die Plattform darf ausschließlich zu dem Zweck genutzt werden, Events zu präsentieren und zu verwalten.
(2) Veranstalter dürfen keine rechtswidrigen, obszönen oder irreführenden Inhalte auf der Plattform veröffentlichen.
(3) Der Plattformbetreiber behält sich das Recht vor, Inhalte, die gegen geltendes Recht oder diese AGB verstoßen, zu entfernen.

§ 5 Kalender und Terminverwaltung
(1) Die Plattform stellt den Veranstaltern ein Kalendersystem zur Verfügung, mit dem sie ihre Events organisieren und verwalten können.
(2) Termine können von den Veranstaltern hinzugefügt, geändert oder gelöscht werden. Der Plattformbetreiber haftet nicht für falsch eingetragene oder nicht mehr aktuelle Termine.

§ 6 Gebühren
(1) Die Nutzung bestimmter Funktionen der Plattform kann kostenpflichtig sein. Die Höhe der Gebühren wird den Nutzern vor Inanspruchnahme der entsprechenden Dienste transparent mitgeteilt.
(2) Die Gebühren sind sofort nach Rechnungsstellung fällig und können über die auf der Plattform angegebenen Zahlungsmethoden beglichen werden.

§ 7 Haftung
(1) Der Plattformbetreiber haftet nur für Schäden, die auf Vorsatz oder grober Fahrlässigkeit beruhen.
(2) Der Plattformbetreiber haftet nicht für die Inhalte, die von den Veranstaltern eingestellt werden, sowie für etwaige Ausfälle oder technische Probleme der Plattform.
(3) Die Veranstalter sind für die Einhaltung aller gesetzlichen Bestimmungen im Zusammenhang mit ihren Events verantwortlich.

§ 8 Datenschutz
Die Verarbeitung personenbezogener Daten erfolgt gemäß der Datenschutzerklärung, die auf der Plattform einsehbar ist.

§ 9 Vertragslaufzeit und Kündigung
(1) Die Nutzung der Plattform ist zeitlich unbegrenzt, sofern nicht anders vereinbart.
(2) Der Nutzer kann sein Benutzerkonto jederzeit ohne Angabe von Gründen kündigen. Der Plattformbetreiber kann das Benutzerkonto bei Verstößen gegen diese AGB nach vorheriger Abmahnung kündigen.

§ 10 Schlussbestimmungen
(1) Änderungen oder Ergänzungen dieser AGB bedürfen der Schriftform.
(2) Sollte eine Bestimmung dieser AGB unwirksam sein oder werden, bleiben die übrigen Bestimmungen unberührt.
(3) Es gilt das Recht der Bundesrepublik Deutschland.
