### ISSUE TITLE
Bootstrap - Deprecated warnings

### ISSUE THREAD

**Issue by stevenobird** [cc-fiae-2024/eventguru-app#56]
Since we're using Bootstrap 5 via SASS, we're tied to their SCSS files.

In the current setup, we're getting some deprecation warnings regarding [nested rules](https://github.com/cc-fiae-2024/eventguru-app/actions/runs/11182807824/job/31089922934#step:5:95) and [color channels](https://github.com/cc-fiae-2024/eventguru-app/actions/runs/11182807824/job/31089922934#step:5:14).  
To get rid of those, we could pin `sass-embedded` from 1.79.x to 1.77.5 via `npm i sass-embedded@1.77.5 --save-exact --save-dev`.

Should be live with those warnings? Bootstrap [won't fix](https://github.com/twbs/bootstrap/issues/40849#issuecomment-2359038505) these deprecations [anytime soon](https://github.com/twbs/bootstrap/issues/40849#issuecomment-2367274006). It is no big issue, since they're just warnings for future versions of sass/dart-sass.

**Comment by Ryuno-Ki** [comment]
![Picard meme "Make it so"](https://github.com/user-attachments/assets/aece03be-1280-4e7a-88d3-4371d4c7a0f3)
